name: Tests CI
on:   [push, pull_request]
jobs:
  jest-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '16.18'
      - name: Install modules
        run: yarn install
      - name: Run Jest tests
        working-directory: server
        run: yarn run test

  cypress-tests:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: postgres://postgres:postgres@localhost:5432/burger-bonanza-react-reducer_e2e
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '16.18'
      
      - name: Install modules
        run: yarn install
      
      - name: Migrate e2e database
        working-directory: server
        run: NODE_ENV=e2e yarn run db:e2e:migrate
      
      - name: Run Cypress
        uses: cypress-io/github-action@v6
        with:
          start: yarn run dev:e2e
          browser: chrome
          headless: true
          wait-on: "http://localhost:3000"
          command: yarn run e2e:run
